### ISSUE TITLE
Grid Search SVM for a good set of parameters

### ISSUE THREAD

**Issue by sjmiller8182** [juhoward/home-credit-default-risk#2]
I am planning on grid search the kernel and the regularization parameter (shown below). Honestly, I'm not sure of the best range for C. We'll see what this yields.

```python
tuned_parameters = [{'C':[0.5, 0.7, 0.8, 0.9, 1.0,
                          1.1, 1.2, 1.3, 1.5],
                    'kernel': ['linear', 'rbf']}]
```

**Comment by schwan1** [comment]
I watched an h20 video on the grid search model. I will look it up and see if they automatically loop through tuning the parameters.
